dist: trusty
language: ruby

cache:
  - bundler
  - apt

services:
  - memcached

addons:
  apt:
    packages:
      - lighttpd
      - libfcgi-dev

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.4
  - 2.3.0

install:
  - gem update --system 2.7.4
  - gem install bundler:1.17.3
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake ci
